# Generated by Django 2.2.1 on 2019-05-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_ativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='preco',
            field=models.FloatField(default=0, verbose_name='Preço das Ações'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ativos',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade de ações'),
            preserve_default=False,
        ),
    ]
