# Generated by Django 2.2.1 on 2019-05-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0006_compraativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraativos',
            name='qtd',
            field=models.IntegerField(default=0, verbose_name='Quantidade comprada'),
            preserve_default=False,
        ),
    ]
