# Generated by Django 2.2.1 on 2019-05-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0008_auto_20190516_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status de venda'),
            preserve_default=False,
        ),
    ]
